export default function Methodology(){return <article className="methodology"><a href="/">Back to the laboratory</a><div className="eyebrow" style={{marginTop:50}}>FLYVISION / METHODOLOGY</div><h1>Real wiring. Modeled activity.</h1><p>The connectome is a structural wiring diagram, not a recording of neural activity. All activation shown here is <strong>connectome-based simulated neural activation</strong>.</p><div className="pipeline">Video frames → visual features → annotated visual input cells → real synaptic graph → simulated activity → dopamine high</div>{[
 ['01 · The real connectome','The default graph contains 18,940 real FlyWire FAFB v783 neurons and 326,400 recorded directed connections. Connectivity comes from the original Shiu research authors’ v783 release, joined to official FlyWire annotations. IDs, counts and annotations are preserved. The bounded subset contains optic, central, visual-projection, descending and motor cells. Missing neuropils remain unavailable.'],
 ['02 · Anatomy','The display uses 78 real neuropil surfaces aligned to FlyWire space. Activity is associated with surfaces by nearest neuron anchor, a display approximation rather than verified neuropil membership. Optional lines represent recorded graph edges.'],
 ['03 · Live video analysis','Compatible MP4 and WebM videos play directly in the browser, without uploading or full-clip preprocessing. A background worker samples frames at up to 20 Hz and 128 × 80 pixels, extracting coarse contrast, motion and expansion cues. Slow devices can skip samples. Seeking resets propagation across the jump. The interpretation toggle visualizes luminance, contrast and temporal change from the same sampled frames; it is not a reconstruction of subjective fly vision.'],
 ['04 · Input populations','Up to 64 annotated neurons per hemisphere from each T4a-d/T5a-d subtype and LC4 provide 1,128 seeds. T4/T5 receive motion/contrast input; LC4 receives expansion input. Scalar gains and field weighting are assumptions; receptive fields are not reconstructed.'],
 ['05 · Propagation','The subset retains all source inputs of at least five synapses into dopamine-positive targets and strongest shortest visual paths within five hops. Full-source incoming counts normalize edge weights. Stable leaky dynamics use ACh excitation, GABA/glutamate inhibition as a coarse approximation, and no fast-current contribution from monoamine-only/unknown cells. Receptor-specific effects are unavailable.'],
 ['06 · Dopamine high','Raw activity averages the 1,535 dopamine-positive annotations, including mixed transmitter labels. The displayed index scales this against fixed blank, contrast, motion, looming, transition and combined-feature references. Zero is the blank baseline and 100 the strongest reference. The scale is fixed across videos at the same graph/settings, and is numerical rather than biological calibration. Raw values and reference metadata remain in exports. Dopamine high records the maximum sampled index.'],
 ['07 · Inspecting a result','The detailed view lets you seek the timeline, replay the peak and inspect an actual neuron ID. Pathways are shortest paths through the loaded real graph, not invented narratives. Structural reachability is not proof of biological causation. The final report deliberately displays one overall score.'],
 ['08 · Procedural demos and comparisons','Built-in stimuli use a lightweight browser feature estimator for instant previews. Live uploads use the same browser estimator; the separate batch API uses OpenCV. Scores from these different extractors should not be compared directly; captured comparisons are cleared when switching extractor or changing parameters. Within the same extractor, A/B timelines compare model response, never animal preference.'],
 ['09 · Limitations','The displayed subset omits most neurons and many incoming and recurrent partners. This signed rate-like model is not the published Shiu LIF model. It omits synaptic kinetics, receptor-specific inhibition, validated retinotopy and biological score calibration. Real anatomy does not make simulated activity a measured neural response. Human saliency and optimization are not implemented.']
 ].map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}<h2>Sources</h2><p><a href="https://github.com/philshiu/Drosophila_brain_model/tree/91bdd1e7dcf193f3e7ca5a8933497fcef63b7960">Pinned connectivity source</a> · <a href="https://github.com/flyconnectome/flywire_annotations/tree/8587524c1748ce5ef2080822a2fc890fc03bf597">Pinned official annotations</a> · <a href="https://www.nature.com/articles/nature12320">T4/T5 motion</a> · <a href="https://www.nature.com/articles/s41586-022-05562-8">LC4 looming</a></p></article>}
